CONFIG += SYMBIAN_USE_IPC_SOCKET
CONFIG += SYMBIAN_USE_DATA_CAGED_DATABASE
CONFIG += SYMBIAN_USE_DATA_CAGED_FILES

contains(CONFIG, SYMBIAN_USE_IPC_SOCKET) \
    || contains(CONFIG, SYMBIAN_USE_DATA_CAGED_DATABASE) \
    || contains(CONFIG, SYMBIAN_USE_DATA_CAGED_FILES) {
    CONFIG += SYMBIAN_THREAD_SAFE_MAILSTORE
}
