######################################################################
# Automatically generated by qmake (2.01a) Thu Mar 5 16:50:58 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += messagedelegate.h messagemodel.h messageviewer.h
FORMS += messageviewerbase.ui
SOURCES += main.cpp messagedelegate.cpp messagemodel.cpp messageviewer.cpp
