######################################################################
# Automatically generated by qmake (2.01a) Thu Mar 5 16:51:11 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += foldermodel.h messagenavigator.h
FORMS += messagenavigatorbase.ui
SOURCES += foldermodel.cpp main.cpp messagenavigator.cpp
